[snowflake]
user = "HOLMES928"
password = "Yuanyuan928"
account = "zr93224.ca-central-1.aws"
warehouse = "COMPUTE_WH"
database = "PETS"
schema = "PUBLIC"

[leancloud]
app_id = "sGq44T5LIVC1z4da0GKsmwMb-gzGzoHsz"
app_key = "KyOU4rvMfTT6MUQD5i3imh8R"
master_key = "Y5uijQNDNSY6ML2iNfqG2hF8"